# Numpy Hands-on

In [4]:
import numpy as np

In [5]:
L=[1,2,3]

In [6]:
A=np.array([1,2,3])

In [8]:
print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [9]:
for i in L:
    print(i)

1
2
3


In [10]:
for i in A:
    print(i)

1
2
3


In [15]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [16]:
#numpy does not support this operation
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [17]:
L=L+[5]
print(L)

[1, 2, 3, 4, 5]


In [18]:
A=A+[4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [19]:
L1=[]
for i in L:
    L1.append(i+i)
print(L1)

[2, 4, 6, 8, 10]


In [20]:
#IMPORTANT "+" in list does concatenation while in numpy id does vector addition
A+A

array([2, 4, 6])

In [21]:
 A*2

array([2, 4, 6])

In [22]:
L*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
#In Lists
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [24]:
#In lists
L2=[]
for i in L:
    L2.append(i*i)
print(L2)

[1, 4, 9, 16, 25]


In [25]:
#In numpy
A**2

array([1, 4, 9])

In [26]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [27]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [28]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
#CONCLUSION
# for performing these 3 above operations in lists , you need for loop whiloe it is not so in numpy.
# Numpy Functions act Element wise.
# for loops in python are slow, so avoid using them.

# DOT PRODUCT

In [29]:
a=np.array([1,2])
b=np.array([2,1])


In [30]:
dot=0
for x,y in zip(a,b):
    dot+=x*y
print(dot)

4


In [31]:
a*b

array([2, 2])

In [32]:
np.sum(a*b)

4

In [33]:
(a*b).sum()

4

In [34]:
np.dot(a,b)

4

In [35]:
a.dot(b)

4

In [36]:
b.dot(a)

4

In [38]:
amag=np.sqrt((a*a).sum())
print(amag)

2.23606797749979


In [40]:
#predefined function for finding magnitude: linalg
amag=np.linalg.norm(a)
print(amag)

2.23606797749979


In [41]:
cosangle=a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
print(cosangle)

0.7999999999999998


In [42]:
#by default in radian
angle = np.arccos(cosangle)
print(angle)

0.6435011087932847


In [44]:
#speed comparision(for loop vs numpy dot product)
import numpy as np
from datetime import datetime
a=np.random.randn(100)
b=np.random.randn(100)
T=100000

def dot_product(a,b):
    result=0
    for e,f in zip(a,b):
        result+=e*f
    return result

t0=datetime.now()
for t in range(T):
    dot_product(a,b)
dt1=datetime.now()-t0
    
t0=datetime.now()
for t in range(T):
    a.dot(b)
dt2=datetime.now()-t0

print("dt1/dt2:",dt1.total_seconds()/dt2.total_seconds())


dt1/dt2: 33.20821000155788


In [45]:
print(datetime.now())

2020-06-24 01:28:53.596537


In [ ]:
#vectors and matrices 

In [51]:
k=np.array([[1,2],[3,4]])
k

array([[1, 2],
       [3, 4]])

In [53]:
L=[[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [54]:
L[0]

[1, 2]

In [55]:
L[0][0]

1

In [56]:
k[0][0]

1

In [57]:
k[0,1]

2

In [58]:
k[0,0]

1

In [59]:
k1=np.matrix([[1,2],[3,4]])
k1

matrix([[1, 2],
        [3, 4]])

In [60]:
A=np.array(k1)
A

array([[1, 2],
       [3, 4]])

In [61]:
A.T

array([[1, 3],
       [2, 4]])

In [63]:
k.T

array([[1, 3],
       [2, 4]])

In [66]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
b=np.ones((5,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
a=np.random.random((5,5))
a

array([[0.87419956, 0.81992782, 0.05452556, 0.58486205, 0.72011254],
       [0.53532248, 0.92141945, 0.80649528, 0.45927698, 0.86590305],
       [0.81777289, 0.18938203, 0.81901229, 0.67137319, 0.83069161],
       [0.02763305, 0.1011265 , 0.4515135 , 0.53280003, 0.0998181 ],
       [0.87500649, 0.02128436, 0.60955204, 0.83239001, 0.40377068]])

In [75]:
a=np.random.randn(10,10)
a

array([[-1.33053078e+00, -5.62715546e-02, -2.92768344e+00,
         1.92245250e+00, -2.41740607e+00, -1.76702592e-01,
        -2.36707157e-01,  9.70062703e-01, -5.08219116e-01,
        -3.52363822e-01],
       [-7.20060616e-01, -1.32249964e+00, -2.63445384e-01,
        -5.91551350e-01, -6.21970915e-01,  2.72371011e-01,
         1.10796436e+00,  5.61429964e-01,  1.55987985e-01,
        -9.63738928e-01],
       [-8.23042466e-01,  1.93190053e+00, -1.93443156e+00,
         3.81195055e-01, -1.34245957e+00, -7.38587129e-01,
         2.39281945e-02, -9.69648121e-01,  1.80264338e+00,
        -2.26599008e-01],
       [-4.40702765e-01, -1.32579598e+00, -7.07704060e-01,
        -3.63592091e-03,  3.06467355e-01,  6.31748162e-01,
         1.33737204e+00,  2.44369477e-01, -2.51896189e+00,
        -3.22857823e-02],
       [ 5.24934939e-01,  2.49036728e-03,  5.07821341e-01,
        -3.37885295e-01, -8.81144600e-01, -4.58321312e-01,
         7.93750383e-01, -6.05607411e-01,  4.45034788e-01,
        -1.

In [76]:
a.mean()

-0.03255699453849426

In [78]:
a.var()

0.9284310447565199

In [80]:
#inverse of a matrix
A=np.array([[1,2],[3,4]])
Ainv=np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [81]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [82]:
np.linalg.det(A)

-2.0000000000000004

In [84]:
np.diag(A)

array([1, 4])

In [85]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [86]:
a=np.array([1,2])
b=np.array([3,4])
print(np.outer(a,b))

[[3 4]
 [6 8]]


In [87]:
np.inner(a,b)
a.dot(b)

11

In [88]:
A

array([[1, 2],
       [3, 4]])

In [89]:
np.diag(A).sum()

5

In [90]:
#inbuilt function for finding array diagonals sum
np.trace(A)

5

In [91]:
 A

array([[1, 2],
       [3, 4]])

In [92]:
b

array([3, 4])

In [94]:
#inbuilt function for solving linear equation
# AX=B
x=np.linalg.solve(A,b)
x

array([-2. ,  2.5])

In [97]:
x=np.linalg.inv(A).dot(b)
x

array([-2. ,  2.5])